credit-card-issuer:
  issuers:
    - name: visa
      startWith: 4
      notStartWith: 4026, 417500, 4508, 4844, 4913, 4917
      length: 13, 16, 19
    - name: MasterCard
      startWith: 51, 52, 53, 54, 55
      length: 16
    - name: Visa Electron
      startWith: 4026, 417500, 4508, 4844, 4913, 4917
      length: 16
    - name: American Express
      startWith: 34, 37
      length: 15
    - name: Discover
      startWith: 6011, 644, 645, 646, 647, 648, 649, 65
      length: 16, 19
    - name: Maestro
      startWith: 5018, 5020, 5038, 5893, 6304, 6759, 6761, 6762, 6763
      length: 16, 17, 18, 19
    - name: InstaPayment
      startWith: 637, 638, 639
      length: 16

